# version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    container_name: lifydb
    volumes:
      - ./postgres:/var/lib/postgresql/data
    env_file:
      - .env

# docker-compose restart
# docker-compose up -d
